require('dotenv').config();
const express = require('express');
const cors = require('cors');
// Make sure to set STRIPE_SECRET_KEY in the .env file.
const stripeSecretKey = process.env.STRIPE_SECRET_KEY || 'sk_test_...';
// Using conditional require/initialization for resilience when missing keys
let stripe = null;
try {
    stripe = require('stripe')(stripeSecretKey);
} catch (e) {
    console.warn('Stripe initialization failed, ensure secret key is correct.');
}

const app = express();

app.use(cors());
app.use(express.static('public'));
app.use(express.json());

// Fake database mapping sessions to generated license keys
const licenseKeys = new Map();

function generateLicenseKey() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let key = 'API-OBS-';
    for (let i = 0; i < 3; i++) {
        for (let j = 0; j < 4; j++) {
            key += chars.charAt(Math.floor(Math.random() * chars.length));
        }
        if (i < 2) key += '-';
    }
    return key;
}

app.post('/create-checkout-session', async (req, res) => {
    if (!stripe) {
        return res.status(500).json({ error: 'Stripe is not configured in the backend.' });
    }

    try {
        const { instanceId } = req.body;

        // Use a placeholder price if the user hasn't set up Stripe properly yet
        // For a real app, you would create a Product and Price in the Stripe Dashboard
        // and pass the price_id here. 

        const session = await stripe.checkout.sessions.create({
            payment_method_types: ['card'],
            line_items: [
                {
                    price_data: {
                        currency: 'usd',
                        product_data: {
                            name: 'API Observatory Pro License',
                            description: 'Unlock unlimited request logging and search.',
                        },
                        unit_amount: 500, // $5.00
                    },
                    quantity: 1,
                },
            ],
            client_reference_id: instanceId || 'anonymous',
            mode: 'payment',
            success_url: `${process.env.FRONTEND_URL || 'http://localhost:3000'}/success?session_id={CHECKOUT_SESSION_ID}`,
            cancel_url: `${process.env.FRONTEND_URL || 'http://localhost:3000'}/cancel`,
        });

        res.json({ url: session.url });
    } catch (error) {
        console.error('Error creating checkout session:', error);
        res.status(500).json({ error: error.message });
    }
});

app.post('/verify-license', async (req, res) => {
    try {
        const { license_key } = req.body;

        // In our simplified logic, any generated key mapping or specific patterns are "valid"
        // Also support the simulation test keys
        const keyUpper = String(license_key).toUpperCase().trim();
        if (keyUpper.startsWith('TEST-') || keyUpper.includes('REDIBALLA')) {
            return res.json({ success: true, message: 'Valid test key' });
        }

        // Check if the key was generated by our Stripe flow
        let found = false;
        for (const [sessionId, key] of licenseKeys.entries()) {
            if (key === keyUpper) {
                found = true;
                break;
            }
        }

        if (found) {
            return res.json({ success: true, message: 'License activated' });
        }

        return res.json({ success: false, message: 'Invalid or unknown license key' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Endpoint to fetch the license key after successful payment
app.get('/verify-session', async (req, res) => {
    if (!stripe) return res.status(500).json({ error: 'Stripe is not configured.' });

    try {
        const { session_id } = req.query;
        if (!session_id) {
            return res.status(400).json({ error: 'Missing session_id' });
        }

        // Retrieve the session from Stripe to ensure it was actually paid
        const session = await stripe.checkout.sessions.retrieve(session_id);

        if (session.payment_status === 'paid') {
            // Check if we already generated a key for this session
            let existingKey = licenseKeys.get(session_id);

            if (!existingKey) {
                // Generate a new key and store it
                existingKey = generateLicenseKey();
                licenseKeys.set(session_id, existingKey);
            }

            return res.json({ success: true, licenseKey: existingKey });
        } else {
            return res.json({ success: false, message: 'Payment not completed.' });
        }
    } catch (error) {
        console.error('Error verifying session:', error);
        res.status(500).json({ error: 'Failed to verify session' });
    }
});

// Standin Success page that the checkout redirects to
app.get('/success', (req, res) => {
    res.send(`
    <html>
      <head>
        <title>Payment Successful</title>
        <style>
          body { font-family: sans-serif; background: #0d1117; color: #fff; text-align: center; padding: 50px; }
          .card { background: #161b22; padding: 30px; border-radius: 10px; display: inline-block; }
          .key { font-family: monospace; font-size: 24px; color: #58a6ff; margin: 20px 0; padding: 10px; background: #000; border: 1px solid #30363d; user-select: all; }
        </style>
      </head>
      <body>
        <div class="card">
          <h1>Payment Successful! 🎉</h1>
          <p>Please wait while we generate your Pro license key...</p>
          <div id="key-container"></div>
          <p style="color: #8b949e; margin-top: 30px;">Copy the key above, go back to the API Observatory extension, and paste it to activate Pro.</p>
        </div>
        
        <script>
          const urlParams = new URLSearchParams(window.location.search);
          const sessionId = urlParams.get('session_id');
          
          if (sessionId) {
            fetch('/verify-session?session_id=' + sessionId)
              .then(res => res.json())
              .then(data => {
                const container = document.getElementById('key-container');
                if (data.success && data.licenseKey) {
                  container.innerHTML = '<div class="key">' + data.licenseKey + '</div>';
                } else {
                  container.innerHTML = '<p style="color: #f85149;">Failed to load license key: ' + (data.message || 'Unknown error') + '</p>';
                }
              })
              .catch(err => {
                document.getElementById('key-container').innerHTML = 'Error loading key: ' + err.message;
              });
          }
        </script>
      </body>
    </html>
  `);
});

app.get('/cancel', (req, res) => {
    res.send(`
    <html>
      <body style="background: #0d1117; color: #fff; text-align: center; padding: 50px; font-family: sans-serif;">
        <h1>Payment Cancelled</h1>
        <p>You can safely close this window and try again later.</p>
      </body>
    </html>
  `);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log('[Payment Server] Running on http://localhost:' + PORT);
    console.log('[Payment Server] Reminder: Set STRIPE_SECRET_KEY in .env to a sk_test_... key!');
});
